services:
  mongo:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=l%40c123
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped

  app:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI='mongodb://admin:l%40c123@mongo:27017/ChaoLongTool?authSource=admin'
    depends_on:
      - mongo
    ports:
      - "80:8080"
    restart: unless-stopped